### ISSUE TITLE
Block displays wrong avatar creation output 

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/mvs-explorer-www#35]
Avatar creation output shows NAN before the avatar name. Transaction page is fine

Example:
https://explorer.mvs.org/blk/1385177

**Comment by LaurentSalou** [comment]
Done in c3191f7
It now display the type of the input or output, like in the transaction page. I have also added a small separator to improve the visibility

![screenshot from 2018-08-03 18-46-23](https://user-images.githubusercontent.com/29446660/43639200-050113e4-974e-11e8-9251-74cb27382cf6.png)

I keep the issue open since the Avatar and Address pages have the same issue

**Comment by LaurentSalou** [comment]
Applied the same to address page in efe2d97
